version: '2'
services:
  web:
    build:
      context: .
      args:
        target:
    ports:
      - "7777:7777"
    environment:
      - DD_AGENT_HOST=agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_ENV=peertesting-blocking-java
      - DD_APPSEC_ENABLED=true
      - DD_TRACE_DEBUG
      - DD_APPSEC_HTTP_BLOCKED_TEMPLATE_HTML
      - DD_APPSEC_HTTP_BLOCKED_TEMPLATE_JSON
    depends_on:
      - "agent"
  agent:
    image: datadog/agent:7.39.0
    environment:
      - DD_API_KEY
      - DD_SITE=datad0g.com
      - DD_ENV=peertesting-blocking-java
      - DD_REMOTE_CONFIGURATION_ENABLED=true
      - DD_REMOTE_CONFIGURATION_REFRESH_INTERVAL=5s
      - DD_REMOTE_CONFIGURATION_KEY
      - DD_REMOTE_CONFIGURATION_CONFIG_ROOT
      - DD_REMOTE_CONFIGURATION_DIRECTOR_ROOT
