version: '2'
services:
  web:
    build:
      context: .
      args:
        target:
    image: sample-peertesting
    container_name: sample-peertesting
    ports:
      - "7777:7777"
    environment:
      - DD_AGENT_HOST=agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_ENV=peertesting-blocking-anna
    volumes:
      - ./logs:/var/log/datadog/dotnet
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "agent"
  agent:
    image: datadog/agent
    container_name: agent-peertesting
    environment:
      - DD_API_KEY
      #- DD_SITE=${DD_SITE:-datad0g.com}
volumes:
  logs: